# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'det_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1771, 1079)
        Form.setMaximumSize(QtCore.QSize(166666, 166666))
        Form.setStyleSheet("QWidget{\n"
"background-color:#eaeaea;\n"
"}")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(180, 120, 1571, 751))
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"margin-top:2ex;\n"
"font-family:微软雅黑;\n"
"font:bold 18px;\n"
"color:#474554;\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"subcontrol-origin:margin;\n"
"subcontrol-position:top right;\n"
"padding:0 3px;\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(10, 30, 651, 711))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("QLabel{\n"
"background-color:#eaeaea;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(self.groupBox_6)
        self.label2.setEnabled(True)
        self.label2.setGeometry(QtCore.QRect(670, 30, 651, 711))
        self.label2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label2.setStyleSheet("QLabel{\n"
"background-color:#eaeaea;\n"
"}")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox.setGeometry(QtCore.QRect(1336, 70, 221, 631))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.t8 = QtWidgets.QLabel(self.groupBox)
        self.t8.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t8.setFont(font)
        self.t8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t8.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t8.setText("")
        self.t8.setAlignment(QtCore.Qt.AlignCenter)
        self.t8.setObjectName("t8")
        self.gridLayout.addWidget(self.t8, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.t2 = QtWidgets.QLabel(self.groupBox)
        self.t2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t2.setFont(font)
        self.t2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t2.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t2.setText("")
        self.t2.setAlignment(QtCore.Qt.AlignCenter)
        self.t2.setObjectName("t2")
        self.gridLayout.addWidget(self.t2, 1, 1, 1, 1)
        self.t6 = QtWidgets.QLabel(self.groupBox)
        self.t6.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t6.setFont(font)
        self.t6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t6.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t6.setText("")
        self.t6.setAlignment(QtCore.Qt.AlignCenter)
        self.t6.setObjectName("t6")
        self.gridLayout.addWidget(self.t6, 5, 1, 1, 1)
        self.t5 = QtWidgets.QLabel(self.groupBox)
        self.t5.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t5.setFont(font)
        self.t5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t5.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t5.setText("")
        self.t5.setAlignment(QtCore.Qt.AlignCenter)
        self.t5.setObjectName("t5")
        self.gridLayout.addWidget(self.t5, 4, 1, 1, 1)
        self.t7 = QtWidgets.QLabel(self.groupBox)
        self.t7.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t7.setFont(font)
        self.t7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t7.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t7.setText("")
        self.t7.setAlignment(QtCore.Qt.AlignCenter)
        self.t7.setObjectName("t7")
        self.gridLayout.addWidget(self.t7, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.t3 = QtWidgets.QLabel(self.groupBox)
        self.t3.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t3.setFont(font)
        self.t3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t3.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t3.setText("")
        self.t3.setAlignment(QtCore.Qt.AlignCenter)
        self.t3.setObjectName("t3")
        self.gridLayout.addWidget(self.t3, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.t4 = QtWidgets.QLabel(self.groupBox)
        self.t4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t4.setFont(font)
        self.t4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t4.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t4.setText("")
        self.t4.setAlignment(QtCore.Qt.AlignCenter)
        self.t4.setObjectName("t4")
        self.gridLayout.addWidget(self.t4, 3, 1, 1, 1)
        self.t1 = QtWidgets.QLabel(self.groupBox)
        self.t1.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t1.setFont(font)
        self.t1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t1.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t1.setText("")
        self.t1.setAlignment(QtCore.Qt.AlignCenter)
        self.t1.setObjectName("t1")
        self.gridLayout.addWidget(self.t1, 0, 1, 1, 1)
        self.t9 = QtWidgets.QLabel(self.groupBox)
        self.t9.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.t9.setFont(font)
        self.t9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t9.setStyleSheet("QLabel{\n"
"color:red;\n"
"background-color:white;\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"}")
        self.t9.setText("")
        self.t9.setAlignment(QtCore.Qt.AlignCenter)
        self.t9.setObjectName("t9")
        self.gridLayout.addWidget(self.t9, 8, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.get_image = QtWidgets.QPushButton(self.groupBox_6)
        self.get_image.setGeometry(QtCore.QRect(110, 130, 481, 481))
        self.get_image.setObjectName("get_image")
        self.result_img = QtWidgets.QPushButton(self.groupBox_6)
        self.result_img.setGeometry(QtCore.QRect(760, 150, 491, 481))
        self.result_img.setObjectName("result_img")
        self.flag = QtWidgets.QLabel(self.groupBox_6)
        self.flag.setGeometry(QtCore.QRect(450, 110, 200, 200))
        self.flag.setMaximumSize(QtCore.QSize(400, 400))
        self.flag.setAutoFillBackground(False)
        self.flag.setStyleSheet("QLabel{\n"
"background-color:rgb(22,22,22,0)\n"
"}")
        self.flag.setText("")
        self.flag.setObjectName("flag")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 600, 160, 271))
        self.groupBox_4.setMaximumSize(QtCore.QSize(160, 16777215))
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"margin-top:2ex;\n"
"font-family:微软雅黑;\n"
"font:bold 18px;\n"
"color:#474554;\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"subcontrol-origin:margin;\n"
"subcontrol-position:top right;\n"
"padding:0 3px;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn5_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn5_1.setGeometry(QtCore.QRect(16, 110, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn5_1.setFont(font)
        self.btn5_1.setStyleSheet("QPushButton{\n"
"text-align : center;\n"
" background-color :#3D3A3A;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 21px;\n"
" color:#E7E4E4\n"
"}\n"
" QPushButton:pressed\n"
"{background-color :#666666;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 20px;\n"
" color:#E7E4E4}\n"
"")
        self.btn5_1.setObjectName("btn5_1")
        self.btn5_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn5_2.setGeometry(QtCore.QRect(16, 30, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn5_2.setFont(font)
        self.btn5_2.setStyleSheet("QPushButton{\n"
"text-align : center;\n"
" background-color :#3D3A3A;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 21px;\n"
" color:#E7E4E4\n"
"}\n"
" QPushButton:pressed\n"
"{background-color :#666666;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 20px;\n"
" color:#E7E4E4}\n"
"")
        self.btn5_2.setObjectName("btn5_2")
        self.btn5_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn5_3.setGeometry(QtCore.QRect(16, 190, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn5_3.setFont(font)
        self.btn5_3.setStyleSheet("QPushButton{\n"
"text-align : center;\n"
" background-color :#3D3A3A;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 21px;\n"
" color:#E7E4E4\n"
"}\n"
" QPushButton:pressed\n"
"{background-color :#666666;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 20px;\n"
" color:#E7E4E4}\n"
"")
        self.btn5_3.setObjectName("btn5_3")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(13, 123, 160, 190))
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(160, 16777215))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"margin-top:2ex;\n"
"font-family:微软雅黑;\n"
"font:bold 18px;\n"
"color:#474554;\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"subcontrol-origin:margin;\n"
"subcontrol-position:top right;\n"
"padding:0 3px;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox4.setGeometry(QtCore.QRect(16, 40, 131, 51))
        self.comboBox4.setStyleSheet(" text-align : center;\n"
" background-color :#3D3A3A;\n"
" font: bold;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 21px;\n"
" color:#E7E4E4\n"
"")
        self.comboBox4.setObjectName("comboBox4")
        self.comboBox4.addItem("")
        self.comboBox4.addItem("")
        self.btn4_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn4_1.setGeometry(QtCore.QRect(16, 120, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn4_1.setFont(font)
        self.btn4_1.setStyleSheet("QPushButton{\n"
"text-align : center;\n"
" background-color :#3D3A3A;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 21px;\n"
" color:#E7E4E4\n"
"}\n"
" QPushButton:pressed\n"
"{background-color :#666666;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 20px;\n"
" color:#E7E4E4}\n"
"")
        self.btn4_1.setObjectName("btn4_1")
        self.groupBox1 = QtWidgets.QGroupBox(Form)
        self.groupBox1.setGeometry(QtCore.QRect(10, 320, 160, 271))
        self.groupBox1.setMaximumSize(QtCore.QSize(160, 16777215))
        self.groupBox1.setStyleSheet("QGroupBox{\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"margin-top:2ex;\n"
"font-family:微软雅黑;\n"
"font:bold 18px;\n"
"color:#474554;\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"subcontrol-origin:margin;\n"
"subcontrol-position:top right;\n"
"padding:0 3px;\n"
"}")
        self.groupBox1.setObjectName("groupBox1")
        self.btn1_1 = QtWidgets.QPushButton(self.groupBox1)
        self.btn1_1.setGeometry(QtCore.QRect(16, 30, 131, 51))
        self.btn1_1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn1_1.setFont(font)
        self.btn1_1.setStyleSheet("QPushButton{\n"
"text-align : center;\n"
" background-color :#3D3A3A;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 21px;\n"
" color:#E7E4E4\n"
"}\n"
" QPushButton:pressed\n"
"{background-color :#666666;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 20px;\n"
" color:#E7E4E4}\n"
"")
        self.btn1_1.setObjectName("btn1_1")
        self.btn1_2 = QtWidgets.QPushButton(self.groupBox1)
        self.btn1_2.setGeometry(QtCore.QRect(16, 110, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn1_2.setFont(font)
        self.btn1_2.setStyleSheet("QPushButton{\n"
"text-align : center;\n"
" background-color :#3D3A3A;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 21px;\n"
" color:#E7E4E4\n"
"}\n"
" QPushButton:pressed\n"
"{background-color :#666666;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 20px;\n"
" color:#E7E4E4}\n"
"")
        self.btn1_2.setObjectName("btn1_2")
        self.btn1_3 = QtWidgets.QPushButton(self.groupBox1)
        self.btn1_3.setGeometry(QtCore.QRect(16, 190, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn1_3.setFont(font)
        self.btn1_3.setStyleSheet("QPushButton{\n"
"text-align : center;\n"
" background-color :#3D3A3A;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 21px;\n"
" color:#E7E4E4\n"
"}\n"
" QPushButton:pressed\n"
"{background-color :#666666;\n"
" font-family:微软雅黑;\n"
" border-color: gray;\n"
" border-width: 0px;\n"
" border-radius: 4px;\n"
" padding: 6px;\n"
" height : 14px;\n"
" border-style: outset;\n"
" font : 20px;\n"
" color:#E7E4E4}\n"
"")
        self.btn1_3.setObjectName("btn1_3")
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 880, 1741, 183))
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
"border: 2px solid #3e3e3e;\n"
"border-radius:5px;\n"
"margin-top:2ex;\n"
"font-family:微软雅黑;\n"
"font:bold 18px;\n"
"color:#474554;\n"
"\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"subcontrol-origin:margin;\n"
"subcontrol-position:top right;\n"
"padding:0 3px;\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.tps = QtWidgets.QTextBrowser(self.groupBox_7)
        self.tps.setGeometry(QtCore.QRect(10, 30, 1711, 141))
        self.tps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tps.setStyleSheet("QTextBrowser{\n"
"border:0px;\n"
"font-family:微软雅黑;\n"
"font:bold 18px;\n"
"color:#4A708B;\n"
"background-color:#F1F1F1\n"
"}\n"
"")
        self.tps.setObjectName("tps")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 1731, 111))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"border: 2px solid #3d3a3a;\n"
"border-radius:5px;\n"
"color:#eaeaea;\n"
"background-color:#3d3a3a;\n"
"}")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 16, 100, 100))
        self.label_12.setStyleSheet("QLabel{\n"
"border-radius:20px;\n"
"background-color:#eaeaea;\n"
"}")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(1490, 94, 261, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{\n"
"border-bottom:5px solid qlineargradient(y0:0, y1:1,stop: 0 white, stop: 1  #3d3a3a);\n"
"border-right:2px solid ;\n"
"background-color:#eaeaea;\n"
"}")
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "工业视觉监测系统ver1.2"))
        self.groupBox_6.setTitle(_translate("Form", "检测内容"))
        self.label.setText(_translate("Form", "待检测图片"))
        self.label2.setText(_translate("Form", "图片检测结果"))
        self.label_9.setText(_translate("Form", "检测总数:"))
        self.label_7.setText(_translate("Form", "缺料:"))
        self.label_6.setText(_translate("Form", "俯损伤:"))
        self.label_5.setText(_translate("Form", "侧损伤:"))
        self.label_8.setText(_translate("Form", "杂质:"))
        self.label_4.setText(_translate("Form", "侧缺料:"))
        self.label_10.setText(_translate("Form", "结果:"))
        self.label_3.setText(_translate("Form", "残留:"))
        self.label_11.setText(_translate("Form", "合格率:"))
        self.get_image.setText(_translate("Form", "PushButton"))
        self.result_img.setText(_translate("Form", "PushButton"))
        self.groupBox_4.setTitle(_translate("Form", "批量检测"))
        self.btn5_1.setText(_translate("Form", "检测"))
        self.btn5_2.setText(_translate("Form", "选择目录"))
        self.btn5_3.setText(_translate("Form", "资源显示"))
        self.groupBox_3.setTitle(_translate("Form", "模式选项"))
        self.comboBox4.setItemText(0, _translate("Form", "  检测模式"))
        self.comboBox4.setItemText(1, _translate("Form", "  评估模式"))
        self.btn4_1.setText(_translate("Form", "模式切换"))
        self.groupBox1.setTitle(_translate("Form", "图片检测"))
        self.btn1_1.setText(_translate("Form", "选择图片"))
        self.btn1_2.setText(_translate("Form", "检测图片"))
        self.btn1_3.setText(_translate("Form", "保存查看"))
        self.groupBox_7.setTitle(_translate("Form", "日志记录"))
        self.label_2.setText(_translate("Form", "工 业 视 觉 监 测 系 统"))
        self.label_13.setText(_translate("Form", "视觉实验室  version:1.2"))
